---
- name: Deploy PostgreSQL server
  become: true
  hosts: AnsibleGroup_appdbs
  gather_facts: false
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:  
  roles:
    - {name: db-tier, tags: [db-tier, dbs, PostgreSQL]}

- name: Deploy application servers
  become: true
  hosts: AnsibleGroup_apps
  gather_facts: true
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:
  roles:
    - {name: app-tier, tags: [app-tier, apps, Tomcat]}

- name: Deploy load balancer servers
  become: true
  hosts: AnsibleGroup_frontends
  gather_facts: true
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:
  roles:
    - {name: lb-tier, haproxy_group: AnsibleGroup_apps, tags: [lb-tier, lbs, HAProxy]}
...
