---
- name: Upgrade PostgreSQL server
  become: true
  hosts: AnsibleGroup_appdbs
  gather_facts: true
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:  
  tasks:
    - name: Call __upgrade.yml from db-tier role
      ansible.builtin.import_role:
        name: db-tier
        tasks_from: __upgrade.yml
...
