---
# tasks file for OracleLinux7 conversion to RHEL
- name: Check for /srv/OracleLinux7/glibc-common directory
  ansible.builtin.stat:
    path: /srv/OracleLinux7/glibc-common
  register: OracleLinux7_glibc_common

- name: Fail if /srv/OracleLinux7/glibc-common directory does not exist
  ansible.builtin.fail:
    msg: "/srv/OracleLinux7/glibc-common directory does not exist, fail playbook run."
  when: OracleLinux7_glibc_common.stat.isdir is not defined and not OracleLinux7_glibc_common.stat.isdir

- name: Find specific glibc-common rpm filename in /srv/OracleLinux7/glibc-common
  ansible.builtin.find:
    paths: /srv/OracleLinux7/glibc-common
    patterns: "*.rpm"
  register: glibc_common_rpm_find

- name: Check var glibc_common_rpm_find.files
  ansible.builtin.debug:
    var: glibc_common_rpm_find.files

- name: Check glibc-common package specific path
  ansible.builtin.debug:
    msg:
      - "basename: {{ glibc_common_rpm_find.files[0].path | basename }}"
      - "dirname:  {{ glibc_common_rpm_find.files[0].path | dirname }}"
      - "realpath: {{ glibc_common_rpm_find.files[0].path | realpath }}"
      - "relpath:  {{ glibc_common_rpm_find.files[0].path | relpath }}"
...
