---
# tasks file for OracleLinux7 conversion to RHEL
- name: Check for /srv/OracleLinux7/glibc-common directory
  ansible.builtin.stat:
    path: /srv/OracleLinux7/glibc-common
  register: OracleLinux7_glibc_common

- name: Fail if /srv/OracleLinux7/glibc-common directory does not exist
  ansible.builtin.fail:
    msg: "/srv/OracleLinux7/glibc-common directory does not exist, exiting..."
  when: OracleLinux7_glibc_common.stat.isdir is not defined and not OracleLinux7_glibc_common.stat.isdir

- name: Find specific glibc-common rpm filename in /srv/OracleLinux7/glibc-common
  ansible.builtin.find:
    paths: /srv/OracleLinux7/glibc-common
    patterns: "glibc-common*.rpm"
  register: glibc_common_rpm_find

- name: Check var glibc_common_rpm_find.files
  ansible.builtin.debug:
    var: glibc_common_rpm_find.files

- name: Fail if glibc-common rpm package is not present
  ansible.builtin.fail:
    msg: "glibc-common rpm package is not present, exiting..."
  when: glibc_common_rpm_find.files[0].path is not defined and glibc_common_rpm_find.files[0].islnk

- name: Check glibc-common package specific path
  ansible.builtin.debug:
    msg:
      - "basename: {{ glibc_common_rpm_find.files[0].path | basename }}"
      - "dirname:  {{ glibc_common_rpm_find.files[0].path | dirname }}"
      - "realpath: {{ glibc_common_rpm_find.files[0].path | realpath }}"
      - "relpath:  {{ glibc_common_rpm_find.files[0].path | relpath }}"

- name: Set variable for glibc-common package basename
  ansible.builtin.set_fact:
    glibc_common_basename: "{{ glibc_common_rpm_find.files[0].path | basename }}"

- name: Check glibc-common package specific path
  ansible.builtin.debug:
    msg:
      - "basename_ext: {{ glibc_common_basename.split('.')[-1] }}"
      - "basename_sansext: {{ glibc_common_basename | splitext | first }}"

- name: Convert glibc-common rpm package to cpio archive
  ansible.builtin.shell: |
    set -o pipefail
    rpm2cpio {{ glibc_common_rpm_find.files[0].path | basename }} > {{ glibc_common_basename | splitext | first }}.cpio
  args:
    executable: /bin/bash
    chdir: "{{ glibc_common_rpm_find.files[0].path | dirname }}"
  register: glibc_common_to_cpio
  changed_when: glibc_common_to_cpio.rc != 0

- name: Extract glibc-common cpio archive
  ansible.builtin.shell: |
    set -o pipefail
    cpio -idmv < {{ glibc_common_basename | splitext | first }}.cpio
  args:
    executable: /bin/bash
    chdir: "{{ glibc_common_rpm_find.files[0].path | dirname }}"
  register: glibc_common_cpio_extract
  changed_when: glibc_common_cpio_extract.rc != 0

- name: Use cpio copy-pass to copy C.utf8 to /usr/lib/locale
  ansible.builtin.shell: |
    set -o pipefail
    find C.utf8/ -depth -print | cpio -pamVd /usr/lib/locale
  args:
    executable: /bin/bash
    chdir: "{{ glibc_common_rpm_find.files[0].path | dirname }}/usr/lib/locale"
  register: glibc_common_cpio_copy_pass
  changed_when: glibc_common_cpio_copy_pass.rc != 0
...
