---
# tasks file for standard db-tier
- ansible.builtin.set_fact:
    postgresql_version_fips: ''

- name: Install PostgreSQL packages
  ansible.builtin.yum:
    name:
      - postgresql-server
      - python-psycopg2
    state: latest

- name: Check if PostgreSQL database is initialized.
  ansible.builtin.stat:
    path: "{{ pg_data }}"
  register: pgdata_dir_version

- name: Perform PostgreSQL database initialization if required.
  ansible.builtin.command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists
  notify:
    - restart_postgresql

- name: Start PostgreSQL service and enable PostgreSQL to start at boot time
  ansible.builtin.service:
    name: postgresql.service
    enabled: yes
    state: started
  notify:
    - restart_postgresql

- name: Confgure PostgreSQL local access
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'local   all             all'
    line: local   all             all                                  trust
  notify:
    - restart_postgresql

- name: Confgure PostgreSQL remote access
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host    all             all             127.0.0.1/32            ident'
    line: host    all             all             0.0.0.0/0            md5
  notify:
    - restart_postgresql

- name: Configure PostgreSQL service listener address binding
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: 'listen_addresses ='
    line: listen_addresses = '*'
  notify:
    - restart_postgresql

- name: Restart PostgreSQL service
  ansible.builtin.service:
    name: postgresql.service
    state: restarted
