---
# tasks file for app-tier
- name: install tomcat packages
  yum:
    name: tomcat
    state: latest

#- name: Print all hostvars variables for AnsibleGroup_appdbs[0]
#  debug: 
#    var: hostvars[groups['AnsibleGroup_appdbs'][0]]

- name: Set tomcat_can_network_connect_db flag on and keep it persistent across reboots
  seboolean:
    name: tomcat_can_network_connect_db
    state: yes
    persistent: yes

- name: create tomcat ROOT directory
  file:
    path: "{{ webapps }}/ROOT"
    state: directory

- name: copy index.html to tomcat webapps ROOT"
  template:
    src: index.html.j2
    dest: "{{ webapps }}/ROOT/index.html"
    mode: 0644
  notify:
    - restart_tomcat

- name: copy mydb.cfg to tomcat user home dir"
  template:
    src: mydb.cfg.j2
    dest: /usr/share/tomcat/mydb.cfg
    mode: 0644
  notify:
    - restart_tomcat

- name: start Tomcat service and enable Tomcat to start at boot time
  service:
    name: tomcat.service
    enabled: yes
  notify:
    - restart_tomcat
